apiVersion: v1
kind: Pod
metadata:
  name: mqtt-client-nodejs
  # The namespace must match the IoT MQ BrokerListener's namespace
  # Otherwise use the long hostname: aio-mq-dmqtt-frontend.azure-iot-operations.svc.cluster.local
  namespace: azure-iot-operations
spec:
  # Use the "mqtt-client" service account which comes with default deployment
  # Otherwise create it with `kubectl create serviceaccount mqtt-client -n azure-iot-operations`
  serviceAccountName: mqtt-client

  containers:
    - name: mqtt-client-nodejs
      image: iot04.azurecr.io/mqtt-subscriber:0.1.6
      imagePullPolicy: IfNotPresent
      volumeMounts:
       - name: mq-sat
         mountPath: /var/run/secrets/tokens
       - name: trust-bundle
         mountPath: /var/run/certs     
      env:
        - name: IOT_MQ_HOST_NAME
          value: "aio-mq-dmqtt-frontend"
        - name: IOT_MQ_PORT
          value: "8883"
        - name: IOT_MQ_TLS_ENABLED
          value: "true"
        - name: IOT_MQ_TOPIC
          value: "azure-iot-operations/data/opc.tcp/opc.tcp-1/thermostat"
  
  imagePullSecrets:
    - name: acr-secret  
  
  volumes:
  - name: mq-sat
    projected:
      sources:
      - serviceAccountToken:
          path: mq-sat
          audience: aio-mq # Must match audience in BrokerAuthentication
          expirationSeconds: 86400
  - name: trust-bundle
    configMap:
      name: aio-ca-trust-bundle-test-only # Default root CA cert
